# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from login_view_model import LoginViewModel
from workspace_window import WorkspaceWindow
import requests

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(382, 227)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.PasswordLine = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordLine.setObjectName("PasswordLine")
        self.verticalLayout_2.addWidget(self.PasswordLine)
        self.LoginLine = QtWidgets.QLineEdit(self.centralwidget)
        self.LoginLine.setObjectName("LoginLine")
        self.verticalLayout_2.addWidget(self.LoginLine)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.enterButton = QtWidgets.QPushButton(self.centralwidget)
        self.enterButton.setObjectName("enterButton")
        self.verticalLayout_2.addWidget(self.enterButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.viewModel = LoginViewModel()
        self.workspaceWindow = WorkspaceWindow()
        self.LoginLine.textChanged.connect(self.viewModel.set_password)
        self.PasswordLine.textChanged.connect(self.viewModel.set_login)
        self.enterButton.clicked.connect(self.check_credentials)



    def check_credentials(self):
        login = self.viewModel.get_login()
        password = self.viewModel.get_password()
        # print(type(login))
        response = requests.post("http://localhost:5000/login", json={"login": login, "password": password})
        if response.status_code == 200:  # проверяем, что запрос был успешным
            try:
                data = response.json()
                if "success" in data and data["success"]:
                    print("Правильный логин или пароль!")
                    self.workspaceWindow.show()
                    self.close()
                else:
                    print("Неправильный логин или пароль!")
            except ValueError:  # если ответ не в формате JSON
                print("Ошибка формата ответа")
        else:
            print("Ошибка сервера")

            # Мне кажется, эти файлы менять ваще нежелательно, лучше стоит добавлять функционал к классам окна, а это оставить как UI.

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Вход в САМД \"Багульник\""))
        self.enterButton.setText(_translate("MainWindow", "PushButton"))
