# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file './design/data_workspace.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.9
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WorkspaceWindow(object):
    def setupUi(self, WorkspaceWindow):
        WorkspaceWindow.setObjectName("WorkspaceWindow")
        WorkspaceWindow.resize(851, 602)
        self.centralwidget = QtWidgets.QWidget(WorkspaceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 50, 211, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 90, 211, 31))
        self.label_2.setObjectName("label_2")
        WorkspaceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WorkspaceWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 26))
        self.menubar.setObjectName("menubar")
        WorkspaceWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WorkspaceWindow)
        self.statusbar.setObjectName("statusbar")
        WorkspaceWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WorkspaceWindow)
        QtCore.QMetaObject.connectSlotsByName(WorkspaceWindow)

    def retranslateUi(self, WorkspaceWindow):
        _translate = QtCore.QCoreApplication.translate
        WorkspaceWindow.setWindowTitle(_translate("WorkspaceWindow", "MainWindow"))
        self.label.setText(_translate("WorkspaceWindow", "Основное окно работы с данными"))
        self.label_2.setText(_translate("WorkspaceWindow", "Пока в процессе работы"))

